### ISSUE TITLE
include phy rate into plot 

### ISSUE THREAD

**Issue by hackrid** [cnlohr/wifirxpower#1]
would you think it's worth the effort to include e.g. the MCS (modulation and coding scheme) index into the plot to have a better understanding what the wifi hardware is doing with the link quality? 

br

**Comment by cnlohr** [comment]
Yes!  I think that would be great!  If we can settle on what we think the best MCS is, I can just use that for all tests moving forward.

**Comment by cnlohr** [comment]
Wait... sorry... I got my projects confused.  Is what you say even possible?

**Comment by hackrid** [comment]
at least it's possible to see these values by issuing some shell command:

iw dev wlan0 link
Connected to 68:7f:74:3b:b0:01 (on wlan0)
        SSID: tesla-5g-bcm
        freq: 5745
        RX: 30206 bytes (201 packets)
        TX: 4084 bytes (23 packets)
        signal: -31 dBm
        tx bitrate: 300.0 MBit/s MCS 15 40Mhz short GI
https://wireless.wiki.kernel.org/en/users/documentation/iw

hope to soon find some time to look more into this

**Comment by cnlohr** [comment]
That would be really cool :-D

**Comment by hackrid** [comment]
i picked up to work on this. unfortunately I noticed that the MCS value is not always provided. Will try to add a bitrate based graph to the plot.
For now[ I use a call to  "iw dev wlan0 station dump"](https://github.com/hackrid/wifirxpower/commit/edb825cae66202c433be324a5c7debe4d17d4df5) to get the values. might not be the fastest option but seems to be fast enough.
